### ISSUE TITLE
Compiling clang hangs

### ISSUE THREAD

**Issue by robertlucyshyn** [sol-prog/clang-cross-armhf#1]
I am having trouble compiling clang according to the instructions in the README. I have Docker desktop installed on a Windows 10 Pro laptop and run the following instructions in Windows Powershell (not Powershell ISE):

```
PS C:\Bob\FRC\clang> git clone https://github.com/sol-prog/clang-cross-armhf.git
Cloning into 'clang-cross-armhf'...
remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 13 (delta 3), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (13/13), done.
PS C:\Bob\FRC\clang> cd clang-cross-armhf
PS C:\Bob\FRC\clang\clang-cross-armhf> docker build -t clang-cross-debian-armhf . > rloutput.txt
```
(In the above, the `> rloutput.txt` is only to redirect output to a file so I can submit the results to this issue.)

The compilation process starts but it eventually hangs at the following:

`[1966/2891] Building CXX object tools/clang/lib/AST/CMakeFiles/clangAST.dir/ASTDumper.cpp.o`

The full output file is attached here:

[rloutput.txt](https://github.com/sol-prog/clang-cross-armhf/files/3337054/rloutput.txt)

Can you provide any assistance to help resolve this issue?

Thanks.

**Comment by sol-prog** [comment]
Can you check how much RAM you have allocated in Docker for the VM ? On Linux Docker can take as much RAM as needed (it doesn't use a VM on Linux), but on Windows and macOS I think you need to edit the max amount of RAM available in the Docker settings. On my machine building Clang takes from 2 to 3.5 - 3.8 GB of RAM. So I assume you'll need at least 4GB.

**Comment by robertlucyshyn** [comment]
Thank you! That fixed it. Originally, I did see the note on setting the amount of RAM but I missed it was referring to a Docker setting. I updated the Docker setting and it worked. Thanks again.
